[package]
name = "xraydb-data"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Serde data model shared by the xraydb crates"
keywords = ["xray", "physics", "science", "no-std"]
categories = ["science", "no-std"]

[dependencies]
serde = { workspace = true }
