[package]
name = "xraydb-wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "WebAssembly bindings for the xraydb X-ray reference database"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
xraydb = { workspace = true }
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
console_error_panic_hook = { workspace = true }
